### ISSUE TITLE
Enable Telnet NAWS Option

### ISSUE THREAD

**Issue by mystiker** [unitopia-de/webmud3#108]
The telnet option NAWS is used to control the output dimensions coming from the mud.

[ ] Send an NAWS subnegotiation everytime the output size of the client changes
or
[ ] Determine useful default value and stick to it

Remarks:

An output length of <79 will not be accepted by Unitopia and default to 79.
Output length is only supported as Wizard and only in Orbit
An output height of <5 will not be accepted by Unitopia and default to 5.
Output height is bound to the "more" feature and can be freely set.

**Comment by myonara** [comment]
The default size is 80x25. Some code in all Muds, especially UNItopia, requires this minimum. Please provide either two parameters during the Docker build or two environment variables to set these minimums when starting the container.
