### ISSUE TITLE
telnet option CHARSET, 

### ISSUE THREAD

**Issue by myonara** [unitopia-de/webmud3#111]
[ ] investigate how it is working and which implementation is the right one
[ ] backend implementation
[ ] frontend implementation / optional display?
[ ] testing

**Comment by mystiker** [comment]
I implemented a first draft in the linked PR but I need help with testing and validation.

Here is a comparison of all supported charsets:

| Encoding                 | Webmud3      | Unitopia    |
|----------------------|-----------------|-------------|
| utf8 (utf-8)              | supported       | supported |
| latin1 (ISO-8859-1) | ~~supported~~       | supported |
| ISO-8859-15           | unsupported   | supported |
| windows-1252        | unsupported   | supported |
| ascii (us-ascii)         | ~~supported~~        | supported |


Please run this code locally to be able to change the CHARSET environment variable accordingly.

See the [PR](https://github.com/unitopia-de/webmud3/pull/122) for more details.

**Comment by mystiker** [comment]
I encountered some problems with different encodings other than utf-8.

After some discussions with fellow wizards, I decided to drop all encoding support, but utf-8.

**Comment by mystiker** [comment]
I revisited the old implementation at master https://github.com/unitopia-de/webmud3/blob/44adfdb473d78e6b90a362108493d6014be45a30/backend/mudSocket.js and as far as I can tell, only UTF-8 was supported - so at least nothing got lost.
