### ISSUE TITLE
Update Contributing Guide

### ISSUE THREAD

**Issue by myonara** [unitopia-de/webmud3#118]
felag:
[ ] Do a Proposal: https://github.com/unitopia-de/webmud3/blob/develop/CONTRIBUTING.md
mudadm@unitopia:
| | Review by amotzkau
| | Review by pumuk
| | Review by MontyZuma
| | Review by myonara

**Comment by mystiker** [comment]
I think a nice update to the readme.md will suffice. Have a look at the changes in the PR.
