### ISSUE TITLE
Support File-Edit

### ISSUE THREAD

**Issue by myonara** [unitopia-de/webmud3#8]
File Edit like [webmud2beta](https://unitopia.de/webmud2beta).

GMCP-Module Files:
MUD -> Client:
- [x] Files.URL { url:"https://www.unitopia.de/filebase/jwt_with_user_mud_file"} URL ready to get (load) or put (save) the file.
- [x] Files.CurrentPath { "path": "/w/myonara" } Show current path.
- [x] Files.DirectoryList { "path": "/w/myonara", "entries" : [ { "name":"workroom.c", "size":3832, "filedate":"28.04.2019", "filetime":"18:30:21", "isDir":0},...] }  

Client-> MUD
- [x] Files.OpenFile { "file": "/w/myonara/ed.tmp" } Request an Files.URL token for a particular file.
- [x] Files.ChDir { "dir": "/w/myonara/public" }

**Comment by amotzkau** [comment]
Suggestion as the editor widget: https://ace.c9.io

It supports syntax highlighting and a lot of other cool stuff for editing LPC files.

**Comment by myonara** [comment]
support of snippets: from global or from local user configuration

**Comment by myonara** [comment]
ace editor is implemented with c_cpp mode for lpc files and text mode for non lpc files. => CLOSED
